- hosts: services
  roles:
    - role: node_systemd_service
      source_folder:  "{{ source_folder }}"
      should_restart: "{{ should_restart }}"
      description: "{{ description }}"
      after: "{{ after }}"
      working_directory: "{{ working_directory }}"
      start_command: "{{ start_command }}"
      restart_policy: "{{ restart_policy }}"
      target: "{{ target }}"
      service_name: "{{ service_name }}"
      node_version: "{{ node_version }}"
      service_account: "{{ service_account }}"
