name: 'Publish Node App'
description: 'Publish Node App to NPM'
inputs:
  node_version:
    required: true
    description: "The node version to use"
    default: 16.x
  npm_token:
    required: true
    description: "The npm access token"
  user_name:
    required: true
    description: "The user name that will be displayed on npm"
  user_email:
    required: true
    description: "The user email that will be displayed on npm"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Use Node.js
    uses: actions/setup-node@v3
    with:
      node-version: ${{ inputs.node_version }}
      cache: 'npm'
  - shell: bash
    run: npm ci
  - shell: bash
    run: 'git config user.email "${{ inputs.user_email }}"'
  - shell: bash
    run: 'git config user.name "${{ inputs.user_name }}"'
  - shell: bash
    if: github.ref == 'refs/heads/main'
    run: npm version minor
  - shell: bash
    if: github.ref == 'refs/heads/main'
    run: git push origin HEAD:main
  - shell: bash
    run: npm config set //registry.npmjs.org/:_authToken ${{ inputs.npm_token}}
    env:
      NODE_ACCESS_TOKEN: ${{ inputs.npm_token }}
  - shell: bash
    run: npm publish --access public