name: Deploy Node Service CI
on:
  push: 
    branches: ['main']
jobs:
  test: 
    runs-on: 'ubuntu-latest'
    steps:

    - uses: curium-rocks/actions/deploy-node-service@main
      with:
        hosts: '[{"hostname": "localhost","connection": "local", "username": "root"}]'
        source_folder: './test/'