name: Deploy Node Service CI
on:
  push: 
    branches: ['main']
    paths:
    - 'deploy-node-service/**'
jobs:
  test: 
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: deploy-node-service
