name: Deploy Node Service CI
on:
  push: 
    branches: ['main']
    paths:
    - 'deploy-node-service/**'
jobs:
  test: 
    runs-on: 'ubuntu-latest'
    steps:
    - uses: curium-rocks/actions/deploy-node-service
